"""Les reponses en dur qui font marcher l'API avant que vous n'ecriviez le depot.

Chaque constante est le resultat REEL de la requete que vous allez ecrire :
quand vous remplacerez `return fixtures.X` par la vraie requete, l'ecran ne
bougera pas - c'est le signe que vous avez juste.

    SANTE          -> chapitre 02
    LISTE          -> chapitre 03
    NOMBRE         -> chapitre 03
    FICHE          -> chapitre 04
    INDEX          -> chapitre 05
    CREATION       -> chapitre 05
    MODIFICATION   -> chapitre 06
    EVOLUTION      -> chapitre 06
    AUTOUR         -> chapitre 08
    ZONE           -> chapitre 08
    STATISTIQUES   -> chapitre 09
    AUDIT          -> chapitre 09
    SCHEMA         -> chapitre 09
    PLAN           -> chapitre 09

Au chapitre 09, ce fichier ne sert plus a rien : supprimez-le.
"""

SANTE = {'mongo': 'ok', 'version': '8.0.30', 'especes': 15}

LISTE = [{'numero': 1,
  'evolutions': [{'titre': 'Pythonet'},
                 {'titre': 'Pythonier'},
                 {'titre': 'Serpython'},
                 {'titre': 'Grand Serpent'}],
  'famille': 'backend',
  'habitats': [{'lieu': 'Station F, Paris',
                'point': {'type': 'Point', 'coordinates': [2.3708, 48.8352]}},
               {'lieu': 'Toulouse',
                'point': {'type': 'Point', 'coordinates': [1.4442, 43.6047]}},
               {'lieu': 'Nantes',
                'point': {'type': 'Point',
                          'coordinates': [-1.5536, 47.2184]}}],
  'langages': ['python'],
  'nom': 'Dev Python',
  'stade': 1,
  'xp': 4200},
 {'numero': 2,
  'evolutions': [{'titre': 'Javaton'},
                 {'titre': 'Javarien'},
                 {'titre': 'Cafetier'},
                 {'titre': 'Maitre des Beans'}],
  'famille': 'backend',
  'habitats': [{'lieu': 'La Defense, Courbevoie',
                'point': {'type': 'Point', 'coordinates': [2.2378, 48.8918]}},
               {'lieu': 'Lille',
                'point': {'type': 'Point', 'coordinates': [3.0573, 50.6292]}},
               {'lieu': 'Lyon Part-Dieu',
                'point': {'type': 'Point',
                          'coordinates': [4.8592, 45.7605]}}],
  'langages': ['java', 'kotlin'],
  'nom': 'Dev Java',
  'stade': 2,
  'xp': 15800},
 {'numero': 3,
  'evolutions': [{'titre': 'Phpiou'},
                 {'titre': 'Elephanteau'},
                 {'titre': 'Elephant'},
                 {'titre': 'Elephantesque'}],
  'famille': 'backend',
  'habitats': [{'lieu': 'Marseille',
                'point': {'type': 'Point', 'coordinates': [5.3698, 43.2965]}},
               {'lieu': 'Montpellier',
                'point': {'type': 'Point',
                          'coordinates': [3.8767, 43.6108]}}],
  'langages': ['php'],
  'nom': 'Dev PHP',
  'stade': 1,
  'xp': 3100},
 {'numero': 4,
  'evolutions': [{'titre': 'Nodounet'},
                 {'titre': 'Nodiste'},
                 {'titre': "Boucle d'Evenements"},
                 {'titre': 'Maitre du Non-Bloquant'}],
  'famille': 'backend',
  'habitats': [{'lieu': 'Paris 2e',
                'point': {'type': 'Point', 'coordinates': [2.3417, 48.8686]}},
               {'lieu': 'Bordeaux',
                'point': {'type': 'Point',
                          'coordinates': [-0.5792, 44.8378]}}],
  'langages': ['javascript', 'typescript'],
  'nom': 'Dev Node',
  'stade': 0,
  'xp': 400},
 {'numero': 5,
  'evolutions': [{'titre': 'Rubiton'},
                 {'titre': 'Rubiste'},
                 {'titre': 'Joaillier'},
                 {'titre': 'Pierre Precieuse'}],
  'famille': 'backend',
  'habitats': [{'lieu': 'Paris 11e',
                'point': {'type': 'Point', 'coordinates': [2.3795, 48.8595]}},
               {'lieu': 'Rennes',
                'point': {'type': 'Point',
                          'coordinates': [-1.6778, 48.1173]}}],
  'langages': ['ruby'],
  'nom': 'Dev Ruby',
  'stade': 2,
  'xp': 9600},
 {'numero': 6,
  'evolutions': [{'titre': 'Angulon'},
                 {'titre': 'Angulaire'},
                 {'titre': 'Trigonometre'},
                 {'titre': 'Grand Angle'}],
  'famille': 'frontend',
  'habitats': [{'lieu': 'La Defense, Puteaux',
                'point': {'type': 'Point', 'coordinates': [2.2306, 48.8867]}},
               {'lieu': 'Grenoble',
                'point': {'type': 'Point',
                          'coordinates': [5.7245, 45.1885]}}],
  'langages': ['typescript'],
  'nom': 'Dev Angular',
  'stade': 2,
  'xp': 11200},
 {'numero': 7,
  'evolutions': [{'titre': 'Reactounet'},
                 {'titre': 'Reactiste'},
                 {'titre': 'Reconciliateur'},
                 {'titre': 'Fibre Vivante'}],
  'famille': 'frontend',
  'habitats': [{'lieu': 'Paris 9e',
                'point': {'type': 'Point', 'coordinates': [2.3387, 48.876]}},
               {'lieu': 'Lyon Confluence',
                'point': {'type': 'Point', 'coordinates': [4.8158, 45.7407]}},
               {'lieu': 'Nice',
                'point': {'type': 'Point', 'coordinates': [7.262, 43.7102]}}],
  'langages': ['javascript', 'typescript'],
  'nom': 'Dev React',
  'stade': 1,
  'xp': 5400},
 {'numero': 8,
  'evolutions': [{'titre': 'Sveltounet'},
                 {'titre': 'Sveltiste'},
                 {'titre': 'Sveltemaitre'},
                 {'titre': 'Compilateur Vivant'}],
  'famille': 'frontend',
  'habitats': [{'lieu': 'Nantes',
                'point': {'type': 'Point',
                          'coordinates': [-1.5536, 47.2184]}},
               {'lieu': 'Lyon 7e',
                'point': {'type': 'Point', 'coordinates': [4.842, 45.7333]}}],
  'langages': ['javascript', 'typescript'],
  'nom': 'Dev Svelte',
  'stade': 0},
 {'numero': 9,
  'evolutions': [{'titre': 'Vuiton'},
                 {'titre': 'Vuiste'},
                 {'titre': 'Panorama'},
                 {'titre': 'Point de Vue'}],
  'famille': 'frontend',
  'habitats': [{'lieu': 'Strasbourg',
                'point': {'type': 'Point', 'coordinates': [7.7521, 48.5734]}},
               {'lieu': 'Toulouse',
                'point': {'type': 'Point',
                          'coordinates': [1.4442, 43.6047]}}],
  'langages': ['javascript', 'typescript'],
  'nom': 'Dev Vue',
  'stade': 1,
  'xp': 6100},
 {'numero': 10,
  'evolutions': [{'titre': 'Notebookeur'},
                 {'titre': 'Analyste'},
                 {'titre': 'Statisticien'},
                 {'titre': 'Oracle des Donnees'}],
  'famille': 'data',
  'habitats': [{'lieu': 'Paris 13e',
                'point': {'type': 'Point', 'coordinates': [2.365, 48.8322]}},
               {'lieu': 'Saclay',
                'point': {'type': 'Point', 'coordinates': [2.1667, 48.7314]}},
               {'lieu': 'Grenoble',
                'point': {'type': 'Point',
                          'coordinates': [5.7245, 45.1885]}}],
  'langages': ['python', 'r', 'sql'],
  'nom': 'Data scientist',
  'stade': 2,
  'xp': 13400},
 {'numero': 11,
  'evolutions': [{'titre': 'Promptineur'},
                 {'titre': 'Affineur'},
                 {'titre': 'Architecte de Modeles'},
                 {'titre': 'Reveilleur de Machines'}],
  'famille': 'data',
  'habitats': [{'lieu': 'Paris 8e',
                'point': {'type': 'Point', 'coordinates': [2.307, 48.8738]}},
               {'lieu': 'Saclay',
                'point': {'type': 'Point',
                          'coordinates': [2.1667, 48.7314]}}],
  'langages': ['python'],
  'nom': 'Specialiste IA',
  'stade': 3,
  'xp': 48000},
 {'numero': 12,
  'evolutions': [{'titre': 'Scriptomane'},
                 {'titre': 'Auditeur'},
                 {'titre': 'Chasseur de Failles'},
                 {'titre': 'Gardien du Perimetre'}],
  'famille': 'securite',
  'habitats': [{'lieu': 'Rennes',
                'point': {'type': 'Point',
                          'coordinates': [-1.6778, 48.1173]}},
               {'lieu': 'Paris 15e',
                'point': {'type': 'Point', 'coordinates': [2.2977, 48.8412]}},
               {'lieu': 'Toulon',
                'point': {'type': 'Point', 'coordinates': [5.928, 43.1242]}}],
  'langages': ['python', 'go', 'bash'],
  'nom': 'Specialiste cybersecurite',
  'stade': 2,
  'xp': 21000},
 {'numero': 13,
  'evolutions': [{'titre': 'Yamlier'},
                 {'titre': 'Pipelinier'},
                 {'titre': 'Orchestrateur'},
                 {'titre': 'Maitre des Nuages'}],
  'famille': 'infra',
  'habitats': [{'lieu': 'Roubaix',
                'point': {'type': 'Point', 'coordinates': [3.1746, 50.6942]}},
               {'lieu': 'Paris 12e',
                'point': {'type': 'Point', 'coordinates': [2.3878, 48.84]}},
               {'lieu': 'Gravelines',
                'point': {'type': 'Point',
                          'coordinates': [2.1281, 50.9861]}}],
  'langages': ['bash', 'go', 'yaml'],
  'nom': 'DevOps',
  'stade': 1,
  'xp': 7300}]

NOMBRE = 13

FICHE = {'_id': '6aa182652e84fe80545bf315',
 'numero': 1,
 'cree_le': '2026-09-01T08:00:00+00:00',
 'evolutions': [{'niveau': 'junior',
                 'titre': 'Pythonet',
                 'annees_xp': 0,
                 'salaire': '34000',
                 'attaques': ['copier-coller de StackOverflow',
                              'print de debug']},
                {'niveau': 'mature',
                 'titre': 'Pythonier',
                 'annees_xp': 3,
                 'salaire': '45000',
                 'attaques': ['comprehension de liste',
                              'annotation de type']},
                {'niveau': 'senior',
                 'titre': 'Serpython',
                 'annees_xp': 7,
                 'salaire': '58000',
                 'attaques': ['decorateur maison', 'profilage']},
                {'niveau': 'gourou',
                 'titre': 'Grand Serpent',
                 'annees_xp': 12,
                 'salaire': '72000',
                 'attaques': ['metaclasse', 'PEP acceptee']}],
 'famille': 'backend',
 'frameworks': ['django', 'fastapi'],
 'gestionnaire_paquets': 'uv',
 'habitats': [{'lieu': 'Station F, Paris',
               'point': {'type': 'Point', 'coordinates': [2.3708, 48.8352]}},
              {'lieu': 'Toulouse',
               'point': {'type': 'Point', 'coordinates': [1.4442, 43.6047]}},
              {'lieu': 'Nantes',
               'point': {'type': 'Point',
                         'coordinates': [-1.5536, 47.2184]}}],
 'langages': ['python'],
 'nom': 'Dev Python',
 'schema_version': 1,
 'stade': 1,
 'type_statique': False,
 'xp': 4200}

INDEX = ['_id_',
 'uniq_numero',
 'famille_numero',
 'langages',
 'geo_habitats',
 'ttl_extinction']

CREATION = 14

MODIFICATION = True

EVOLUTION = {'_id': '6aa182652e84fe80545bf315',
 'numero': 1,
 'cree_le': '2026-09-01T08:00:00+00:00',
 'evolutions': [{'niveau': 'junior',
                 'titre': 'Pythonet',
                 'annees_xp': 0,
                 'salaire': '34000',
                 'attaques': ['copier-coller de StackOverflow',
                              'print de debug']},
                {'niveau': 'mature',
                 'titre': 'Pythonier',
                 'annees_xp': 3,
                 'salaire': '45000',
                 'attaques': ['comprehension de liste',
                              'annotation de type']},
                {'niveau': 'senior',
                 'titre': 'Serpython',
                 'annees_xp': 7,
                 'salaire': '58000',
                 'attaques': ['decorateur maison', 'profilage']},
                {'niveau': 'gourou',
                 'titre': 'Grand Serpent',
                 'annees_xp': 12,
                 'salaire': '72000',
                 'attaques': ['metaclasse', 'PEP acceptee']}],
 'famille': 'backend',
 'frameworks': ['django', 'fastapi'],
 'gestionnaire_paquets': 'uv',
 'habitats': [{'lieu': 'Station F, Paris',
               'point': {'type': 'Point', 'coordinates': [2.3708, 48.8352]}},
              {'lieu': 'Toulouse',
               'point': {'type': 'Point', 'coordinates': [1.4442, 43.6047]}},
              {'lieu': 'Nantes',
               'point': {'type': 'Point',
                         'coordinates': [-1.5536, 47.2184]}}],
 'langages': ['python'],
 'nom': 'Dev Python',
 'schema_version': 1,
 'stade': 1,
 'type_statique': False,
 'xp': 4200}

AUTOUR = [{'numero': 2,
  'evolutions': [{'titre': 'Javaton'},
                 {'titre': 'Javarien'},
                 {'titre': 'Cafetier'},
                 {'titre': 'Maitre des Beans'}],
  'famille': 'backend',
  'habitats': [{'lieu': 'La Defense, Courbevoie',
                'point': {'type': 'Point', 'coordinates': [2.2378, 48.8918]}},
               {'lieu': 'Lille',
                'point': {'type': 'Point', 'coordinates': [3.0573, 50.6292]}},
               {'lieu': 'Lyon Part-Dieu',
                'point': {'type': 'Point',
                          'coordinates': [4.8592, 45.7605]}}],
  'langages': ['java', 'kotlin'],
  'nom': 'Dev Java',
  'stade': 2,
  'xp': 15800},
 {'numero': 7,
  'evolutions': [{'titre': 'Reactounet'},
                 {'titre': 'Reactiste'},
                 {'titre': 'Reconciliateur'},
                 {'titre': 'Fibre Vivante'}],
  'famille': 'frontend',
  'habitats': [{'lieu': 'Paris 9e',
                'point': {'type': 'Point', 'coordinates': [2.3387, 48.876]}},
               {'lieu': 'Lyon Confluence',
                'point': {'type': 'Point', 'coordinates': [4.8158, 45.7407]}},
               {'lieu': 'Nice',
                'point': {'type': 'Point', 'coordinates': [7.262, 43.7102]}}],
  'langages': ['javascript', 'typescript'],
  'nom': 'Dev React',
  'stade': 1,
  'xp': 5400},
 {'numero': 8,
  'evolutions': [{'titre': 'Sveltounet'},
                 {'titre': 'Sveltiste'},
                 {'titre': 'Sveltemaitre'},
                 {'titre': 'Compilateur Vivant'}],
  'famille': 'frontend',
  'habitats': [{'lieu': 'Nantes',
                'point': {'type': 'Point',
                          'coordinates': [-1.5536, 47.2184]}},
               {'lieu': 'Lyon 7e',
                'point': {'type': 'Point', 'coordinates': [4.842, 45.7333]}}],
  'langages': ['javascript', 'typescript'],
  'nom': 'Dev Svelte',
  'stade': 0}]

ZONE = [{'numero': 1,
  'evolutions': [{'titre': 'Pythonet'},
                 {'titre': 'Pythonier'},
                 {'titre': 'Serpython'},
                 {'titre': 'Grand Serpent'}],
  'famille': 'backend',
  'habitats': [{'lieu': 'Station F, Paris',
                'point': {'type': 'Point', 'coordinates': [2.3708, 48.8352]}},
               {'lieu': 'Toulouse',
                'point': {'type': 'Point', 'coordinates': [1.4442, 43.6047]}},
               {'lieu': 'Nantes',
                'point': {'type': 'Point',
                          'coordinates': [-1.5536, 47.2184]}}],
  'langages': ['python'],
  'nom': 'Dev Python',
  'stade': 1,
  'xp': 4200},
 {'numero': 2,
  'evolutions': [{'titre': 'Javaton'},
                 {'titre': 'Javarien'},
                 {'titre': 'Cafetier'},
                 {'titre': 'Maitre des Beans'}],
  'famille': 'backend',
  'habitats': [{'lieu': 'La Defense, Courbevoie',
                'point': {'type': 'Point', 'coordinates': [2.2378, 48.8918]}},
               {'lieu': 'Lille',
                'point': {'type': 'Point', 'coordinates': [3.0573, 50.6292]}},
               {'lieu': 'Lyon Part-Dieu',
                'point': {'type': 'Point',
                          'coordinates': [4.8592, 45.7605]}}],
  'langages': ['java', 'kotlin'],
  'nom': 'Dev Java',
  'stade': 2,
  'xp': 15800},
 {'numero': 4,
  'evolutions': [{'titre': 'Nodounet'},
                 {'titre': 'Nodiste'},
                 {'titre': "Boucle d'Evenements"},
                 {'titre': 'Maitre du Non-Bloquant'}],
  'famille': 'backend',
  'habitats': [{'lieu': 'Paris 2e',
                'point': {'type': 'Point', 'coordinates': [2.3417, 48.8686]}},
               {'lieu': 'Bordeaux',
                'point': {'type': 'Point',
                          'coordinates': [-0.5792, 44.8378]}}],
  'langages': ['javascript', 'typescript'],
  'nom': 'Dev Node',
  'stade': 0,
  'xp': 400},
 {'numero': 5,
  'evolutions': [{'titre': 'Rubiton'},
                 {'titre': 'Rubiste'},
                 {'titre': 'Joaillier'},
                 {'titre': 'Pierre Precieuse'}],
  'famille': 'backend',
  'habitats': [{'lieu': 'Paris 11e',
                'point': {'type': 'Point', 'coordinates': [2.3795, 48.8595]}},
               {'lieu': 'Rennes',
                'point': {'type': 'Point',
                          'coordinates': [-1.6778, 48.1173]}}],
  'langages': ['ruby'],
  'nom': 'Dev Ruby',
  'stade': 2,
  'xp': 9600},
 {'numero': 6,
  'evolutions': [{'titre': 'Angulon'},
                 {'titre': 'Angulaire'},
                 {'titre': 'Trigonometre'},
                 {'titre': 'Grand Angle'}],
  'famille': 'frontend',
  'habitats': [{'lieu': 'La Defense, Puteaux',
                'point': {'type': 'Point', 'coordinates': [2.2306, 48.8867]}},
               {'lieu': 'Grenoble',
                'point': {'type': 'Point',
                          'coordinates': [5.7245, 45.1885]}}],
  'langages': ['typescript'],
  'nom': 'Dev Angular',
  'stade': 2,
  'xp': 11200},
 {'numero': 7,
  'evolutions': [{'titre': 'Reactounet'},
                 {'titre': 'Reactiste'},
                 {'titre': 'Reconciliateur'},
                 {'titre': 'Fibre Vivante'}],
  'famille': 'frontend',
  'habitats': [{'lieu': 'Paris 9e',
                'point': {'type': 'Point', 'coordinates': [2.3387, 48.876]}},
               {'lieu': 'Lyon Confluence',
                'point': {'type': 'Point', 'coordinates': [4.8158, 45.7407]}},
               {'lieu': 'Nice',
                'point': {'type': 'Point', 'coordinates': [7.262, 43.7102]}}],
  'langages': ['javascript', 'typescript'],
  'nom': 'Dev React',
  'stade': 1,
  'xp': 5400},
 {'numero': 10,
  'evolutions': [{'titre': 'Notebookeur'},
                 {'titre': 'Analyste'},
                 {'titre': 'Statisticien'},
                 {'titre': 'Oracle des Donnees'}],
  'famille': 'data',
  'habitats': [{'lieu': 'Paris 13e',
                'point': {'type': 'Point', 'coordinates': [2.365, 48.8322]}},
               {'lieu': 'Saclay',
                'point': {'type': 'Point', 'coordinates': [2.1667, 48.7314]}},
               {'lieu': 'Grenoble',
                'point': {'type': 'Point',
                          'coordinates': [5.7245, 45.1885]}}],
  'langages': ['python', 'r', 'sql'],
  'nom': 'Data scientist',
  'stade': 2,
  'xp': 13400},
 {'numero': 11,
  'evolutions': [{'titre': 'Promptineur'},
                 {'titre': 'Affineur'},
                 {'titre': 'Architecte de Modeles'},
                 {'titre': 'Reveilleur de Machines'}],
  'famille': 'data',
  'habitats': [{'lieu': 'Paris 8e',
                'point': {'type': 'Point', 'coordinates': [2.307, 48.8738]}},
               {'lieu': 'Saclay',
                'point': {'type': 'Point',
                          'coordinates': [2.1667, 48.7314]}}],
  'langages': ['python'],
  'nom': 'Specialiste IA',
  'stade': 3,
  'xp': 48000},
 {'numero': 12,
  'evolutions': [{'titre': 'Scriptomane'},
                 {'titre': 'Auditeur'},
                 {'titre': 'Chasseur de Failles'},
                 {'titre': 'Gardien du Perimetre'}],
  'famille': 'securite',
  'habitats': [{'lieu': 'Rennes',
                'point': {'type': 'Point',
                          'coordinates': [-1.6778, 48.1173]}},
               {'lieu': 'Paris 15e',
                'point': {'type': 'Point', 'coordinates': [2.2977, 48.8412]}},
               {'lieu': 'Toulon',
                'point': {'type': 'Point', 'coordinates': [5.928, 43.1242]}}],
  'langages': ['python', 'go', 'bash'],
  'nom': 'Specialiste cybersecurite',
  'stade': 2,
  'xp': 21000},
 {'numero': 13,
  'evolutions': [{'titre': 'Yamlier'},
                 {'titre': 'Pipelinier'},
                 {'titre': 'Orchestrateur'},
                 {'titre': 'Maitre des Nuages'}],
  'famille': 'infra',
  'habitats': [{'lieu': 'Roubaix',
                'point': {'type': 'Point', 'coordinates': [3.1746, 50.6942]}},
               {'lieu': 'Paris 12e',
                'point': {'type': 'Point', 'coordinates': [2.3878, 48.84]}},
               {'lieu': 'Gravelines',
                'point': {'type': 'Point',
                          'coordinates': [2.1281, 50.9861]}}],
  'langages': ['bash', 'go', 'yaml'],
  'nom': 'DevOps',
  'stade': 1,
  'xp': 7300}]

STATISTIQUES = [{'nombre': 5,
  'xp_total': 33100,
  'sans_xp': 0,
  'habitats': 12,
  'famille': 'backend',
  'salaire_gourou_moyen': 72000.0},
 {'nombre': 4,
  'xp_total': 22700,
  'sans_xp': 1,
  'habitats': 9,
  'famille': 'frontend',
  'salaire_gourou_moyen': 71000.0},
 {'nombre': 2,
  'xp_total': 61400,
  'sans_xp': 0,
  'habitats': 5,
  'famille': 'data',
  'salaire_gourou_moyen': 93500.0},
 {'nombre': 1,
  'xp_total': 7300,
  'sans_xp': 0,
  'habitats': 3,
  'famille': 'infra',
  'salaire_gourou_moyen': 80000.0},
 {'nombre': 1,
  'xp_total': 21000,
  'sans_xp': 0,
  'habitats': 3,
  'famille': 'securite',
  'salaire_gourou_moyen': 88000.0}]

AUDIT = [{'champ': '_id', 'presents': 15, 'taux': 100, 'types': ['objectId']},
 {'champ': 'cree_le', 'presents': 15, 'taux': 100, 'types': ['date']},
 {'champ': 'evolutions', 'presents': 15, 'taux': 100, 'types': ['array']},
 {'champ': 'famille', 'presents': 15, 'taux': 100, 'types': ['string']},
 {'champ': 'habitats', 'presents': 15, 'taux': 100, 'types': ['array']},
 {'champ': 'nom', 'presents': 15, 'taux': 100, 'types': ['string']},
 {'champ': 'numero', 'presents': 15, 'taux': 100, 'types': ['int']},
 {'champ': 'schema_version', 'presents': 15, 'taux': 100, 'types': ['int']},
 {'champ': 'stade', 'presents': 15, 'taux': 100, 'types': ['int']},
 {'champ': 'langages', 'presents': 14, 'taux': 93, 'types': ['array']},
 {'champ': 'xp', 'presents': 14, 'taux': 93, 'types': ['int']},
 {'champ': 'frameworks', 'presents': 7, 'taux': 47, 'types': ['array']},
 {'champ': 'gestionnaire_paquets',
  'presents': 6,
  'taux': 40,
  'types': ['string']},
 {'champ': 'type_statique', 'presents': 6, 'taux': 40, 'types': ['bool']},
 {'champ': 'bundler', 'presents': 4, 'taux': 27, 'types': ['string']},
 {'champ': 'reactivite', 'presents': 4, 'taux': 27, 'types': ['string']},
 {'champ': 'taille_bundle_ko', 'presents': 4, 'taux': 27, 'types': ['int']},
 {'champ': 'eteinte_le', 'presents': 2, 'taux': 13, 'types': ['date']},
 {'champ': 'gpu_requis', 'presents': 2, 'taux': 13, 'types': ['bool']},
 {'champ': 'librairies', 'presents': 2, 'taux': 13, 'types': ['array']},
 {'champ': 'niveau_maths', 'presents': 2, 'taux': 13, 'types': ['int']},
 {'champ': 'astreinte', 'presents': 1, 'taux': 7, 'types': ['bool']},
 {'champ': 'certifications', 'presents': 1, 'taux': 7, 'types': ['array']},
 {'champ': 'chapeau', 'presents': 1, 'taux': 7, 'types': ['string']},
 {'champ': 'habilitation', 'presents': 1, 'taux': 7, 'types': ['string']},
 {'champ': 'language', 'presents': 1, 'taux': 7, 'types': ['string']},
 {'champ': 'nuages', 'presents': 1, 'taux': 7, 'types': ['array']},
 {'champ': 'outils', 'presents': 1, 'taux': 7, 'types': ['array']}]

SCHEMA = {'validation': {},
 'niveau': 'off',
 'action': '-',
 'index': [{'v': 2, 'key': {'_id': 1}, 'name': '_id_'},
           {'v': 2,
            'key': {'numero': 1},
            'name': 'uniq_numero',
            'unique': True},
           {'v': 2,
            'key': {'famille': 1, 'numero': 1},
            'name': 'famille_numero'},
           {'v': 2, 'key': {'langages': 1}, 'name': 'langages'},
           {'v': 2,
            'key': {'habitats.point': '2dsphere'},
            'name': 'geo_habitats',
            '2dsphereIndexVersion': 3},
           {'v': 2,
            'key': {'eteinte_le': 1},
            'name': 'ttl_extinction',
            'partialFilterExpression': {'eteinte_le': {'$type': 'date'}},
            'expireAfterSeconds': 2592000}]}

PLAN = {'isCached': False,
 'stage': 'FETCH',
 'inputStage': {'stage': 'IXSCAN',
                'keyPattern': {'famille': 1, 'numero': 1},
                'indexName': 'famille_numero',
                'isMultiKey': False,
                'multiKeyPaths': {'famille': [], 'numero': []},
                'isUnique': False,
                'isSparse': False,
                'isPartial': False,
                'indexVersion': 2,
                'direction': 'forward',
                'indexBounds': {'famille': ['["backend", "backend"]'],
                                'numero': ['[MinKey, MaxKey]']}}}
